### ISSUE TITLE
Current General Structure

### ISSUE THREAD

**Issue by Utkar5hM** [NITK-KODE/competition-management-system#9]
### Discussed in https://github.com/NITK-KODE/competition-management-system/discussions/8

<div type='discussions-op-text'>

<sup>Originally posted by **Utkar5hM** September 13, 2021</sup>
Current General structure for the backend

Type of Users

- Admins: Will basically handle the entire system.
- Mods: can Approve events created by event managers, can add Organizations and event managers to organizations.
- Eventmanagers: can handle Organizations, add members into organizations.
- users; just normal members who can join events participate can showcase awards into their profile

Now users will have points which they can earn by winning events, (haven't considered points by participating yet but can be done)

Now Routes
- /Organizations: from here u can view organizations.  their events, create events, handle events
- /organizations/organizationId/events : from here u can handle events , basically create events, etc.
- /organizations/organizationId/events/eventId/awards: for managing awards  . there will be set of templates given from which one can choose or go for the default ones.
- /events : for getting complete list of events. active(not completed) or completed events.
- /users : for managing personal users. 
- /users/username: for getting a profile page, where stuff will be showcased.

This kind of gives a fair idea. 
Removing the previous Mod event manager dashboard, now they can handle stuff from Organization board itself.

</div>

**Comment by priyansh32** [comment]
A bit off topic but, I have added Airbnb style guide, It is still giving lots of warnings in repo!

run `npm run lint`, can someone just resolve all warnings and create a pull request!

I think we should strictly follow a style guide. I will later set up a actions workflow to lint code on any pull request
